### ISSUE TITLE
Issue with easy ui5 project creation 

### ISSUE THREAD

**Issue by developedbysom** [SAP/generator-easy-ui5#112] opened 2022-08-15 11:58 UTC
Hello,

Issue with easy ui5 project creation 

## Easy-Ui5 version:

> Run `yo easy-ui5 --plugins` to print all relevant version strings
Node.js: v16.13.0
yeoman-environment: 3.10.0
generator-easy-ui5: 3.5.0
home: C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\generator-easy-ui5
pluginsHome: C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\generator-easy-ui5\plugin-generators

Available generators:
  - ui5-project: 0.2.0
  - 
## OS/version:
windows 10
## Steps to reproduce the problem:

1. Step 1
Run yo from command line / use template wizard
2. Step 2
  select easy-ui5 followed by project
3. Step 3

## What is the expected result?
Should prompt for project creation details 
## What happens instead?
✖ An error occurred while running easy-ui5:app#prompting
Error

Cannot find module 'object-assign-deep'
## Any other information? (attach screenshot if possible)

This issue persists from CLI as well as from Template.

- Thanks, Somnath

**Comment by petermuessig** [comment] 2022-08-22 05:50
Hi Somnath,

the issue is related to https://github.com/ui5-community/generator-ui5-project/issues/27. It is a bit confusing error. Can you try the following command and see whether this fixes the issue? 

```
yo easy-ui5 project --forceUpdate
```

It reloads the template again and runs `npm install`.

Best regards, Peter

**Comment by petermuessig** [comment] 2022-09-10 10:21
No update, hence I'm closing the issue

**Closed by petermuessig** 2022-09-10 10:21 UTC

**Comment by franciscofreitas2001** [comment] 2022-12-08 10:18
Hello Peter, I am having the same issue reported in this issue and I've tried the recommended command but the "Cannot find module 'object-assign-deep'" error persists.  

My OS is a macOS Catalina

**Comment by nicoschoenteich** [comment] 2022-12-09 10:04
Hi @franciscofreitas2001,
Can you run `yo easy-ui5 --plugins` and share the output? Also, which subgenerator did you try to run? When applying the `--forceUpdate` fix, make sure to call it with the subgenerator you are trying to reinstall (not neccessarily `project`, could also be `library`,`control`, etc.)
Best, Nico

**Comment by franciscofreitas2001** [comment] 2022-12-09 12:46
Hello @nicoschoenteich ,
thanks for the quick reply.
Here is my output of yo easy-ui5 --plugins:

 ```
    _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Welcome to the easy-ui5 │
   `---------´   │     3.5.1 generator!     │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Node.js: v18.3.0
yeoman-environment: 3.13.0
generator-easy-ui5: 3.5.1
home: /usr/local/lib/node_modules/generator-easy-ui5
pluginsHome: /usr/local/lib/node_modules/generator-easy-ui5/plugin-generators

Available generators:
  - ui5-project: 0.2.1
```
I am trying to run the project subgenerator but today it worked.

I didnt see a version change but today I was able to generate a project.

Thanks

Best Regards
Francisco
