### ISSUE TITLE
Add SAP NetWeaver as a target platform 

### ISSUE THREAD

**Issue by ThomasSwolfs** [SAP/generator-easy-ui5#24] opened 2020-03-22 18:06 UTC
Easy-Ui5 version: 1.3.1 

OS/version: any

Browser/version (+device/version): any

Steps to reproduce the problem:
1. Generating a new app and choosing the target platform

What is the expected result?
Add SAP NetWeaver as a target platform 

What happens instead?
/

Any other information? (attach screenshot if possible)
Are there any plans on adding SAP Netweaver as a target platform? Could we use nwabap-ui5uploader to add the possibility to deploy an application to a Netweaver system?
You guys have any input on this & could I work on this?

**Comment by IObert** [comment] 2020-03-23 08:46
Hi Thomas,

I agree that this would be a useful feature. The problem is that this generator is not a product/tool from SAP, it is currently just a side-project of an SAP employee who doesn't have a NetWeaver background (me). Therefore, the feature has been pending for a while now. 

If you have some time and motivation to implement the feature and create a PR, I'd be more than happy to merge it.

If you want, we can also set up a short call so I can explain the yeoman framework to get you started.

Regards,
Marius

**Comment by ThomasSwolfs** [comment] 2020-03-25 16:04
Hi Marius,

Sounds good! For the moment I'm trying to figure out the best approach to setup my local UI5 project and deploy it to a SAP backend. When this works fine, I'd like to implement it into the generator so it can be reused.

I would like to have this call with you. For me it's also a side-project, so I will send you an e-mail one of these days to align our agendas!

Kind regards,
Thomas

**Comment by IObert** [comment] 2020-03-25 17:21
Sounds great, I'm looking forward to this!

**Comment by rnng** [comment] 2020-04-06 13:13
Hey, 
just have a look on [this package.json](https://github.com/missionmobile/myUI5App/blob/master/package.json). I made a little PoC with this little tool: https://github.com/nrdev88/nwabap-ui5uploader
It uses the commands ui5 build --clean-dest && npx nwabap upload and the file .nwabaprc for deployment to abap repository.
BR,
Gunnar

**Comment by ThomasSwolfs** [comment] 2020-04-06 13:32
Hi Gunnar,

I think this is indeed the way to go, that's how I'm doing it also at the moment! I will try to include it in the generator.

Thomas

**Comment by henloh** [comment] 2020-06-05 09:18
Hello. great work. Creating new apps is realy simple. In my own take on a tool like this i sloved the netweaver/abap deploy. You can just copy and use it I think, its called "Ui5AppGenerator"

**Comment by geert-janklaps** [comment] 2020-06-12 15:06
Hi @IObert,

I added this functionality in following [branch](https://github.com/geert-janklaps/generator-easy-ui5/tree/sap-netweaver).

Generating a new project:
![image](https://user-images.githubusercontent.com/2744548/84516507-2dcef600-acce-11ea-8bd5-148557b4cb1d.png)

Update the UI5.yaml file:
![image](https://user-images.githubusercontent.com/2744548/84516566-40e1c600-acce-11ea-9342-2d3d576d96c2.png)

![image](https://user-images.githubusercontent.com/2744548/84516596-4dfeb500-acce-11ea-9af4-87068520a8c6.png)

Run build:
![image](https://user-images.githubusercontent.com/2744548/84516622-56ef8680-acce-11ea-9781-93db5e3fbd11.png)

![image](https://user-images.githubusercontent.com/2744548/84516634-5bb43a80-acce-11ea-9808-4f2b6c506dda.png)

Result in ABAP repository:
![image](https://user-images.githubusercontent.com/2744548/84516670-679ffc80-acce-11ea-8399-91ebae52a37b.png)

After doing the necessary launchpad configuration / role assignments:
![image](https://user-images.githubusercontent.com/2744548/84516718-78e90900-acce-11ea-9220-b6c1e0cdc446.png)

I'm thinking of adding some additional questions when generating a SAP NetWeaver project, to fill in some of the placeholders I put in the ui5.yaml file and moving the system settings to a separate .env file. (which is supported by the ui5-task-nwabap-deployer I added to the generator. (but I want to keep the commits small for starters)

Do you want to test some things yourself or do you want me to create a pull request right away?

Regards,
Geert-Jan

**Comment by IObert** [comment] 2020-06-15 09:29
Thanks for your contribution, the pull request looks great! I just merged it and triggered the deployment of the next version to npm.

For the next iteration, can you please add test cases for the new "platform" to `test/basic.js` as well? Currently, these cases will fail as the ui5tooling is not able to finish the build successfully.

**Closed** 2020-06-15 09:29 UTC
